[gcp_service_account]
type = "service_account"
project_id = "watch-dashboard-464414"
private_key_id = "6f7fdcd36c285deb70f7f85bef750096799b7532"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDVXkgJrE0XVUkH\\nhaVap/Nnwe0g0872ZGE/ZMnsEoOlJsH3SnkvFCntE5bqLxEIZpYBFU1SdKBWLogd\\nmhYx+lOV4mJnCyo2Zh5e9e9Z1rlmF6vYvgiBvx36ktI057hU0h/DjF9u45O1rCRZ\\nA1pMN3AfoDde0/iauOyaeyBaJ0V4Mp3InmDOEoq33K4SBq1i6q/Vvooe45U2PmCL\\ngvJ9wcM965Qyo60l97ek8PRNK6y/CBWIqISovu+Dr9gC3Wp2MX/rJvQNoFnjuLK2\\nfJ3rwdkl0mjApguzRt8AW7gqg+sNP37ostoViXI63QB4NU9yiQLzCGF1jyTav5dZ\\nT5RZ55b/AgMBAAECggEAHTlAFEnBTKMAO85Yvagc5PGr45/5tp08r+eYkRkKEdp9\\n8juvibyxGgkMVaqOTSsWfDMpjNPEys5YaKGG97UUXL_
client_email = "watch-dashboard-service@watch-dashboard-464414.iam.gserviceaccount.com"
client_id = "105840983234861705256"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/watch-dashboard-service%40watch-dashboard-464414.iam.gserviceaccount.com"
